name: update gh-pages from new_design branch

on:
  push:
    branches: new_design

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # replace with your Node.js version

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run deploy

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          branch: gh-pages
          folder: static/summit2024