name: Dispatch to summit.g0v.tw

on:
  push:
    branches: [ production ]  # replace with your branch

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GHA_WORKFLOW_TRIGGER }}  # replace PAT with your secret's name
          repository: g0v/summit.g0v.tw  # replace with Repo A's path
          event-type: update